spring.application.name=Student

spring.datasource.url=jdbc:mysql://root:wKsGejcxdMGfngLGchPpPcvKjCZtqZHZ@caboose.proxy.rlwy.net:46675/railway

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
